import { useState } from "react";
import {
  useListTasks, getListTasksQueryKey,
  useCreateTask, useCompleteTask
} from "@workspace/api-client-react";
import type { Task, TaskInput } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Plus, CheckCircle2, Calendar, Target, Building2, User } from "lucide-react";
import { formatDate } from "@/lib/format";
import { Badge } from "@/components/ui/badge";

export function TasksTab({ orgId, canManage }: { orgId: string, canManage?: boolean }) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [formOpen, setFormOpen] = useState(false);

  const { data: tasks, isLoading } = useListTasks(orgId, {
    query: { queryKey: getListTasksQueryKey(orgId) }
  });

  const completeTask = useCompleteTask();

  if (isLoading) return <div className="h-64 skeleton rounded-xl"></div>;

  const handleComplete = (task: Task) => {
    completeTask.mutate(
      { orgId, taskId: task.id },
      {
        onSuccess: () => {
          toast({ title: "Task completed" });
          queryClient.invalidateQueries({ queryKey: getListTasksQueryKey(orgId) });
        },
        onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" })
      }
    );
  };

  const openTasks = tasks?.filter(t => t.status !== 'completed' && t.status !== 'cancelled') || [];
  const completedTasks = tasks?.filter(t => t.status === 'completed') || [];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold font-display">Tasks</h2>
          <p className="text-sm text-muted-foreground">Action items generated by AI or team members.</p>
        </div>
        <Button className="gap-2" onClick={() => setFormOpen(true)}>
          <Plus className="h-4 w-4" /> Create Task
        </Button>
      </div>

      <div className="space-y-6">
        <div>
          <h3 className="text-sm font-semibold font-display text-muted-foreground uppercase tracking-wider mb-3">To Do</h3>
          <div className="grid gap-3">
            {openTasks.length === 0 ? (
              <div className="text-center py-8 bg-card border border-primary/10 rounded-lg">
                <CheckCircle2 className="h-8 w-8 text-muted-foreground mx-auto mb-2 opacity-50" />
                <p className="text-sm text-muted-foreground">All caught up!</p>
              </div>
            ) : (
              openTasks.map(task => (
                <div key={task.id} className="bg-card border border-primary/10 rounded-lg p-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="flex items-start gap-3">
                    <Button
                      variant="outline"
                      size="icon"
                      className="h-6 w-6 rounded-full shrink-0 border-primary/30 hover:bg-success hover:border-success hover:text-success-foreground"
                      onClick={() => handleComplete(task)}
                      disabled={completeTask.isPending}
                    >
                      <CheckCircle2 className="h-4 w-4 opacity-0 hover:opacity-100 transition-opacity" />
                    </Button>
                    <div>
                      <h4 className="font-medium text-foreground">{task.title}</h4>
                      {task.description && <p className="text-xs text-muted-foreground mt-1 line-clamp-1">{task.description}</p>}
                      <div className="flex flex-wrap gap-2 mt-2">
                        {task.priority && (
                          <Badge variant="outline" className={`text-[10px] uppercase font-mono ${
                            task.priority === 'high' ? 'text-destructive border-destructive/30' :
                            task.priority === 'medium' ? 'text-warning border-warning/30' : 'text-success border-success/30'
                          }`}>
                            {task.priority} Priority
                          </Badge>
                        )}
                        {task.dueDate && (
                          <span className="text-[10px] text-muted-foreground font-mono flex items-center gap-1">
                            <Calendar className="h-3 w-3" /> Due: {formatDate(task.dueDate)} {task.dueTime}
                          </span>
                        )}
                        {task.type && (
                          <span className="text-[10px] text-primary/70 font-mono flex items-center gap-1 border border-primary/10 px-1 rounded">
                            {task.type}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col gap-1 items-end text-xs text-muted-foreground font-mono bg-background/50 p-2 rounded">
                    {task.accountId && <div className="flex items-center gap-1"><Building2 className="h-3 w-3"/> Account {task.accountId.slice(-4)}</div>}
                    {task.opportunityId && <div className="flex items-center gap-1"><Target className="h-3 w-3"/> Opp {task.opportunityId.slice(-4)}</div>}
                    {task.assignedToUserId && <div className="flex items-center gap-1"><User className="h-3 w-3"/> User {task.assignedToUserId.slice(-4)}</div>}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {completedTasks.length > 0 && (
          <div>
            <h3 className="text-sm font-semibold font-display text-muted-foreground uppercase tracking-wider mb-3">Recently Completed</h3>
            <div className="space-y-2 opacity-60">
              {completedTasks.slice(0, 5).map(task => (
                <div key={task.id} className="flex items-center gap-3 text-sm bg-card/50 p-2 rounded border border-border/50">
                  <CheckCircle2 className="h-4 w-4 text-success" />
                  <span className="line-through">{task.title}</span>
                  <span className="text-xs font-mono ml-auto">{task.completedAt ? formatDate(task.completedAt) : ''}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {formOpen && (
        <TaskFormDialog orgId={orgId} onClose={() => setFormOpen(false)} onSave={() => queryClient.invalidateQueries({ queryKey: getListTasksQueryKey(orgId) })} />
      )}
    </div>
  );
}

function TaskFormDialog({ orgId, onClose, onSave }: { orgId: string, onClose: () => void, onSave: () => void }) {
  const { toast } = useToast();
  const createTask = useCreateTask();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<any>("medium");
  const [type, setType] = useState<any>("call");

  const pending = createTask.isPending;

  const handleSave = () => {
    const payload: TaskInput = {
      title, description, priority, type, status: "open"
    };

    createTask.mutate({ orgId, data: payload }, {
      onSuccess: () => { toast({ title: "Task created" }); onSave(); onClose(); },
      onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" })
    });
  };

  return (
    <Dialog open onOpenChange={(v) => !v && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="font-display">Create Task</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 pt-4">
          <div className="space-y-2">
            <Label>Title</Label>
            <Input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Follow up on proposal" />
          </div>
          <div className="space-y-2">
            <Label>Description</Label>
            <Input value={description} onChange={e => setDescription(e.target.value)} />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Priority</Label>
              <Select value={priority} onValueChange={setPriority}>
                <SelectTrigger><SelectValue/></SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Low</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Type</Label>
              <Select value={type} onValueChange={setType}>
                <SelectTrigger><SelectValue/></SelectTrigger>
                <SelectContent>
                  <SelectItem value="call">Call</SelectItem>
                  <SelectItem value="email">Email</SelectItem>
                  <SelectItem value="meeting">Meeting</SelectItem>
                  <SelectItem value="todo">To-do</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>

        <DialogFooter className="mt-4">
          <Button variant="ghost" onClick={onClose}>Cancel</Button>
          <Button onClick={handleSave} disabled={pending || !title}>
            {pending ? "Saving..." : "Save Task"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}